### ISSUE TITLE
As a developer, I want to be able to load the daily information so that the information can be tracked.

### ISSUE THREAD

**Issue by shadowlessprog** [andreaaa15/Super-Warehouse#1]

**Comment by andreaaa15** [comment]
As a developer, I want to be able to load the daily information so that the information can be tracked.

Acceptance Criteria:
User should be able to see a text box for the list of members and another text box for the list of products
The user should be able to click a member from the member list
Member information pops up in another window

Done: 
Safely implement and output the information from the files into a textbox (GUI). The GUI will have two text boxes, one for a list of members and another for the product list. Once the window opens, the list of members and products will already be displayed. If a member is clicked, another window will pop up and display all their information, including their name, membership ID, membership expiration data and their membership type (either basic or preferred). 

Tasks:
Read the files as input
Store the files in a class
Save class in directory class or struct

Story Points: 2
