### ISSUE TITLE
As a user, I want to see the revenue and the total products sold so that I can keep track of how many products sold in the warehouse.

### ISSUE THREAD

**Issue by Xutherx** [andreaaa15/Super-Warehouse#3]
I wrote the tasks that we have to start to develop in our program. I also wrote the definition of done about we must have ready for Monday. Please check
Tasks:
1. we need to create a class that get all the information of the customers and save them in the private members of the class. Also using a dynamic array to save those. ( completed)
2.  Make member functions to get to the private information of the class.(completed)
3. make a member function to calculate the rebate amount and the amount spent by year per customer.
4. create function to output the information of the customer. The total amount spent and rebate data for each member will be already updated.( in progress)
5.  create a function that output the list of items with the quantities that were sold that day.
6.. create a function that output the members who shopped that day with their respectively membership number and kind.
7. create a function that take as input the membership number, and output the list of the total purchased per that member.
8. create a function that output the total purchases by all the members sorted by membership number and also it should output the grand total of the purchases.
9. create a function that take as input the item name and return it the quantity of that item sold as well as the total sales price.
10. create a function that output the quality of each item sold sorted by item name.
11. create a function that output the rebate of all the preferred members sorted by membership number.
12. create a function that calculate and output the amount per year paid by each member for the memberships dues sorted by membership type.
13.  create a function that takes as input the month from the users and output a list of all members whose memberships expire that month as well as their dues amount.
14. create a function that let the user to add more members. The function then will put for default some purchases to validate the members.
15. create a function that calculate if any basic customer should convert their membership to preferred status or vice versa.
16.  update the information each time.

Definition of done.
1.	The class container has been created and the information of the customers of the first day file has been saved to the dynamic array in the class.  
2.	Creating the member variables for the information of the customers and a function to output all the information of the customers that have been taken.

**Comment by andreaaa15** [comment]
As a user, I want to see the revenue and the total products sold so that I can keep track of how many products sold in the warehouse.

Acceptance Criteria:
Total revenue of the warehouse can be calculated
Total products sold by the warehouse can be calculated
The total revenue and total products sold are calculated correctly
Outputted to GUI

Done: 
Correctly calculate the total revenue of the warehouse and the total products sold by the warehouse. There will be a button to display the information about the warehouse, which will be on the top left corner of the window, under a tab called “Reports”. Under the “Reports” tab, there will be a drop down window called “Products”. In the “Products” tab, there will be more options. The options include the “Products Sold” button and “Total Products Sold with Members” button. The information about total products sold will be displayed once the “Products Sold” button is clicked. This information includes the total revenue of the warehouse and the total products sold by the warehouse. Once this button to display the information about the warehouse is clicked, another window will pop up, displaying the calculated information. The calculations should be correct when they are displayed.

Tasks:
Function/ member variable to store items 
Function to output the list of items with the quantity sold that day and to calculate the total earnings from each product.
Output the quantity of each item sold sorted in alphabetical order

Story Point: 3-4
